SET DB_CLOSE_DELAY -1;
;
CREATE USER IF NOT EXISTS SA SALT 'ee25eda2ea755700' HASH 'd3c150f4e141fd8da9fe742f221b64637efad96e798f4fe33bc30128eceb6f0c' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FFA70097_AAFA_43DB_8443_000EA4E130A6 START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A8536BC3_34C1_4FE9_94C8_6B30381523E9 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_72D4F362_290C_48A3_A629_B69F8A3D8707 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_018FD366_50FB_4B3E_A197_73561B8CA79D START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_80576536_90BB_4BC5_9AFC_DD5CD1F3C39D START WITH 1 BELONGS_TO_TABLE;

CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DB61ABDC_F870_40A8_B64B_97C0162AE13F START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AE30C4C7_491E_41FB_A5A9_BBA22FBB5008 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_11949B63_6C36_411B_BF1A_CC476D535309 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_13B4B360_E70B_41C7_9F5A_EB2E659699AD START WITH 2 BELONGS_TO_TABLE;

CREATE MEMORY TABLE PUBLIC.BASKET(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_018FD366_50FB_4B3E_A197_73561B8CA79D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_018FD366_50FB_4B3E_A197_73561B8CA79D,
    VERSION BIGINT,
    PERSON_ID INTEGER NOT NULL
);
ALTER TABLE PUBLIC.BASKET ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BASKET;
CREATE MEMORY TABLE PUBLIC.BASKET_ATTRIBUTES(
    BASKET_ATTRIBUTE_ID INTEGER NOT NULL,
    VALUE VARCHAR(255),
    KEY VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.BASKET_ATTRIBUTES ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(BASKET_ATTRIBUTE_ID, KEY);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BASKET_ATTRIBUTES;
CREATE MEMORY TABLE PUBLIC.BASKET_PRODUCTS(
    BASKET_ID INTEGER NOT NULL,
    PRODUCTS_ID INTEGER NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BASKET_PRODUCTS;
CREATE MEMORY TABLE PUBLIC.ORDER_TABLE(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A8536BC3_34C1_4FE9_94C8_6B30381523E9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A8536BC3_34C1_4FE9_94C8_6B30381523E9,
    VERSION BIGINT,
    DATE DATE,
    PRICE DOUBLE,
    PERSON_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL
);
ALTER TABLE PUBLIC.ORDER_TABLE ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_TABLE;
CREATE MEMORY TABLE PUBLIC.PERSON(
    ADDRESS1 VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    ZIP_CODE VARCHAR(255),
    CREATION_DATE DATE,
    ID INTEGER NOT NULL
);
ALTER TABLE PUBLIC.PERSON ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;
CREATE MEMORY TABLE PUBLIC.PRODUCT(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_72D4F362_290C_48A3_A629_B69F8A3D8707) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_72D4F362_290C_48A3_A629_B69F8A3D8707,
    VERSION BIGINT,
    description clob,
    image BLOB,
    NAME VARCHAR(255),
    PRICE DECIMAL(19, 2)
);
ALTER TABLE PUBLIC.PRODUCT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
CREATE MEMORY TABLE PUBLIC.PROGRAM_EVENT(
    PROGRAM_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    EVENT_DATE DATE,
    PROGRAM_EVENT VARCHAR(255)
);
ALTER TABLE PUBLIC.PROGRAM_EVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_20 PRIMARY KEY(PROGRAM_ID, USER_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROGRAM_EVENT;
CREATE MEMORY TABLE PUBLIC.USER(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_80576536_90BB_4BC5_9AFC_DD5CD1F3C39D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_80576536_90BB_4BC5_9AFC_DD5CD1F3C39D,
    VERSION BIGINT,
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255)
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27E PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
ALTER TABLE PUBLIC.BASKET ADD CONSTRAINT PUBLIC.UK_JJ3EYTTNGA903AAOJH91BA0CK UNIQUE(PERSON_ID);
ALTER TABLE PUBLIC.BASKET ADD CONSTRAINT PUBLIC.FKL5JJB7KJHN3KA1617YT24DGWD FOREIGN KEY(PERSON_ID) REFERENCES PUBLIC.PERSON(ID) NOCHECK;
ALTER TABLE PUBLIC.BASKET_ATTRIBUTES ADD CONSTRAINT PUBLIC.FK8LRRI2WSLOUSU3KSR57E7R98J FOREIGN KEY(BASKET_ATTRIBUTE_ID) REFERENCES PUBLIC.BASKET(ID) NOCHECK;
ALTER TABLE PUBLIC.ORDER_TABLE ADD CONSTRAINT PUBLIC.FKSY1VJCEL74CC1KQU4QPRJDV4C FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
ALTER TABLE PUBLIC.BASKET_PRODUCTS ADD CONSTRAINT PUBLIC.FKSAN6AIHCKITEOTJD77P913CTW FOREIGN KEY(PRODUCTS_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
ALTER TABLE PUBLIC.PERSON ADD CONSTRAINT PUBLIC.FKHJNO7THTVH0D7W2W9UCFMIGEJ FOREIGN KEY(ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.ORDER_TABLE ADD CONSTRAINT PUBLIC.FKNHUVKI9YHYNRNS6VEK8OE9L0H FOREIGN KEY(PERSON_ID) REFERENCES PUBLIC.PERSON(ID) NOCHECK;
ALTER TABLE PUBLIC.BASKET_PRODUCTS ADD CONSTRAINT PUBLIC.FKLF7FABAQRKLUTTRQCBDIKNOCI FOREIGN KEY(BASKET_ID) REFERENCES PUBLIC.BASKET(ID) NOCHECK;


CREATE MEMORY TABLE PUBLIC.EMPLOYEE(
    ADDRESS1 VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    ZIP_CODE VARCHAR(255),
    EXTERNAL BOOLEAN,
    STATUS INTEGER,
    ID INTEGER NOT NULL
);

ALTER TABLE PUBLIC.EMPLOYEE ADD CONSTRAINT PUBLIC.CONSTRAINT_75 PRIMARY KEY(ID);

ALTER TABLE PUBLIC.EMPLOYEE ADD CONSTRAINT PUBLIC.FKD8IL4LXW1WI74QH8B7UOY6E0A FOREIGN KEY(ID) REFERENCES PUBLIC.USER(ID) NOCHECK;

CREATE MEMORY TABLE PUBLIC.PERSONAL_INFO(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DB61ABDC_F870_40A8_B64B_97C0162AE13F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DB61ABDC_F870_40A8_B64B_97C0162AE13F,
    VERSION BIGINT,
    BIRTH_DATE DATE,
    FLOR VARCHAR(255),
    OFFICE VARCHAR(255),
    PLACE VARCHAR(255),
    TITLE VARCHAR(255),
    WORK_ADDRESS VARCHAR(255),
    WORK_CITY VARCHAR(255),
    EMPLOYEE_ID INTEGER
);
ALTER TABLE PUBLIC.PERSONAL_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PERSONAL_INFO ADD CONSTRAINT PUBLIC.FKOOKBAPE4AGEVJ0ETVLJX3UWAP FOREIGN KEY(EMPLOYEE_ID) REFERENCES PUBLIC.EMPLOYEE(ID) NOCHECK;

CREATE MEMORY TABLE PUBLIC.PROJECT(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AE30C4C7_491E_41FB_A5A9_BBA22FBB5008) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AE30C4C7_491E_41FB_A5A9_BBA22FBB5008,
    VERSION BIGINT,
    NAME VARCHAR(255),
    OWNER VARCHAR(255)
);
ALTER TABLE PUBLIC.PROJECT ADD CONSTRAINT PUBLIC.CONSTRAINT_185 PRIMARY KEY(ID);
CREATE MEMORY TABLE PUBLIC.EMPLOYEE_PROJECTS(
    EMPLOYEE_ID INTEGER NOT NULL,
    PROJECTS_ID INTEGER NOT NULL
);
ALTER TABLE PUBLIC.EMPLOYEE_PROJECTS ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(EMPLOYEE_ID, PROJECTS_ID);

CREATE MEMORY TABLE PUBLIC.UNIT(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_11949B63_6C36_411B_BF1A_CC476D535309) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_11949B63_6C36_411B_BF1A_CC476D535309,
    VERSION BIGINT,
    NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.UNIT ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);

ALTER TABLE PUBLIC.UNIT ADD CONSTRAINT PUBLIC.UK_AA58C9DE9EU0V585LE47W25MY UNIQUE(NAME);

CREATE MEMORY TABLE PUBLIC.UNIT_EMPLOYEES(
    UNIT_ID INTEGER NOT NULL,
    EMPLOYEES_ID INTEGER NOT NULL
);
ALTER TABLE PUBLIC.UNIT_EMPLOYEES ADD CONSTRAINT PUBLIC.UK_HEENFN07AJD1K8FXTNXSJYARG UNIQUE(EMPLOYEES_ID);
ALTER TABLE PUBLIC.UNIT_EMPLOYEES ADD CONSTRAINT PUBLIC.FKQAD0S93SLIK172DRFKI7Y5NEV FOREIGN KEY(UNIT_ID) REFERENCES PUBLIC.UNIT(ID) NOCHECK;
ALTER TABLE PUBLIC.UNIT_EMPLOYEES ADD CONSTRAINT PUBLIC.FKKO86FLXVFPURBC0FLUNY3KLQM FOREIGN KEY(EMPLOYEES_ID) REFERENCES PUBLIC.EMPLOYEE(ID) NOCHECK;

ALTER TABLE PUBLIC.EMPLOYEE_PROJECTS ADD CONSTRAINT PUBLIC.FK97JL81FSRBBLKQFOQWG2O7YPS FOREIGN KEY(EMPLOYEE_ID) REFERENCES PUBLIC.EMPLOYEE(ID) NOCHECK;
ALTER TABLE PUBLIC.EMPLOYEE_PROJECTS ADD CONSTRAINT PUBLIC.FKG10A7UHO2LYLW8G080L5J4GYK FOREIGN KEY(PROJECTS_ID) REFERENCES PUBLIC.PROJECT(ID) NOCHECK;

CREATE MEMORY TABLE PUBLIC.BOOK(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FFA70097_AAFA_43DB_8443_000EA4E130A6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FFA70097_AAFA_43DB_8443_000EA4E130A6,
    VERSION BIGINT,
    AUTHOR VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ISBN VARCHAR(255),
    TITLE VARCHAR(255),
    DOCUMENT_ID INTEGER
);
ALTER TABLE PUBLIC.BOOK ADD CONSTRAINT PUBLIC.CONSTRAINT_17 PRIMARY KEY(ID);

CREATE MEMORY TABLE PUBLIC.DOCUMENT(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_13B4B360_E70B_41C7_9F5A_EB2E659699AD) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_13B4B360_E70B_41C7_9F5A_EB2E659699AD,
    VERSION BIGINT,
    DATA BLOB,
    TYPE INTEGER
);
ALTER TABLE PUBLIC.DOCUMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.BOOK ADD CONSTRAINT PUBLIC.FK62E1MK4IS3LDOR7VQV6Q9E2H6 FOREIGN KEY(DOCUMENT_ID) REFERENCES PUBLIC.DOCUMENT(ID) NOCHECK;
